[package]
name = "cm-hardware"
version = "0.1.0"
edition = "2024"

[dependencies]
cm-core = { workspace = true }
cm-cabinet = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[dev-dependencies]
serde_json = "1"
