[package]
name = "cm-hardware"
version = "0.1.0"
edition = "2024"

[dependencies]
cm-core = { workspace = true }
cm-cabinet = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
